Import Debian version 37~deb12u1
usrmerge (37~deb12u1) bookworm; urgency=medium
.
  * Non-maintainer upload.
  * Rebuild for bookworm.
.
usrmerge (37) unstable; urgency=medium
.
  [ Johannes Schauer Marin Rodrigues ]
  * Use $DPKG_ROOT in usr-is-merged.postinst. (Closes: #1050755)
.
usrmerge (36) unstable; urgency=medium
.
  * Added code by Andreas Beckmann to clean up the biarch libraries
    directories when they are not needed. (Closes: #1038853)
  * Changed postinst to not run convert-etc-shells again on already
    converted systems and to run update-shells to make sure that the
    new shells.state file introduced in bookworm is up to date.
    (Closes: #1033167)
  * Improved the instructions to deal with a mounted /lib/modules/,
    which can also happen on some Xen-based systems. (Closes: 1034346)
  * Greatly improved the error messages when commands execution fails
    (see #1037362).
  * Added a versioned conflict with libc-bin, only relevant for the
    conversion script. (Closes: #1037362)
  * Added a versioned conflict with dhcpcd. (Closes: #1038832)
  * Added a versioned conflict with libparted1.8-10. (Closes: #1038832)
  * Added a versioned conflict with lustre-utils. (Closes: #1038832)

diff --git a/debian/usrmerge.postinst b/debian/usrmerge.postinst
--- a/debian/usrmerge.postinst
+++ b/debian/usrmerge.postinst
@@ -1,4 +1,5 @@
-#!/bin/sh -e
+#!/bin/sh
+set -e
 
 is_fs() {
   local fs_type
@@ -47,6 +48,29 @@ END
   fi
 
   /usr/lib/usrmerge/convert-usrmerge || return $?
+
+  if which update-shells > /dev/null; then
+    update-shells
+  fi
+  /usr/lib/usrmerge/convert-etc-shells || return $?
+}
+
+cleanup_biarch_dirs() {
+  dpkg --compare-versions "$2" lt "36~" || return 0
+
+  # bootstrapping or earlier conversions may have created empty biarch
+  # directories and links. glibc 2.35-4 or later will create them if needed,
+  # so clean up the unused (and unowned) ones
+  local arch_directories="/lib64 /lib32 /libo32 /libx32"
+  for dir in $arch_directories; do
+    [ -e "$dir" ] || continue
+    if ! dpkg-query -S $dir >/dev/null 2>&1; then
+      rm -v $dir
+      if [ -e /usr$dir ] && ! dpkg-query -S /usr$dir >/dev/null 2>&1 ; then
+        rmdir --ignore-fail-on-non-empty -v /usr$dir
+      fi
+    fi
+  done
 }
 
 case "$1" in
@@ -59,7 +83,7 @@ case "$1" in
 	  echo "W: /etc/unsupported-skip-usrmerge-conversion exists." >&2
 	else
 	  maybe_convert "$@" || { echo "E: usrmerge failed." >&2; exit 1; }
-	  /usr/lib/usrmerge/convert-etc-shells
+	  cleanup_biarch_dirs
 	fi
     ;;
 esac
